l_english:
 SETTING_AUTOSAVE:0 "ﻲﺋﺎﻘﻠﺘﻟﺍ ﻆﻔﺤﻠﻟ ﻲﻨﻣﺰﻟﺍ ﻞﺻﺎﻔﻟﺍ"
 SETTING_DEBUG_SAVES:0 "ﺎﻬﻈﻔﺣ ﻢﺗ ﻲﺘﻟﺍ ﺢﻴﺤﺼﺘﻟﺍ ﺕﺍﺮﻣ ﺩﺪﻋ"
 SETTING_TUTORIAL:0 "ﺔﻴﻤﻴﻠﻌﺘﻟﺍ ﺓﺭﻭﺪﻟﺍ"
 SETTING_DISABLED_HINTS:0 " ﺕﺎﺤﻴﻤﻠﺘﻟﺍ ﺀﺎﻐﻟﺍﺇ"
 SETTING_FOCUS_ON_COMBAT:0 "ﻝﺎﺘﻘﻟﺍ ﻰﻠﻋ ﺰﻛﺭ"
 SETTING_REALM_BORDERS_AGAINST_WATER:0 "ﻞﺣﺍﻮﺴﻟﺍ ﻰﻠﻋ ﺔﻜﻠﻤﻤﻟﺍ ﺩﻭﺪﺣ"
 SETTING_TOOLTIP_DELAY:1 "ﺢﻴﻤﻠﺗ ﺮﻴﺧﺄﺗ"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nﺕﺍﻭﺩﻷﺍ ﺕﺎﺤﻴﻤﻠﺗ ﺭﻮﻬﻇ ﻞﺒﻗ ﺮﻴﺧﺄﺘﻟﺍ ﻂﺒﻀﻳ."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "ﺮﻴﺧﺄﺘﻟﺍ ﺢﺘﻓ"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nﺕﺍﻭﺩﻷﺍ ﺕﺎﺤﻴﻤﻠﺗ ﻞﻔﻗ ﺀﺎﻐﻟﺇ ﻞﺒﻗ ﺮﻴﺧﺄﺘﻟﺍ ﻂﺒﻀﻳ."
 SETTING_TOOLTIP_LOCK_TIME:0 "ﻞﻔﻘﻟﺍ ﺮﻴﺧﺄﺗ"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nﺕﺍﻭﺩﻷﺍ ﺕﺎﺤﻴﻤﻠﺗ ﻞﻔﻗ ﻞﺒﻗ ﺮﻴﺧﺄﺘﻟﺍ ﻂﺒﻀﻳ."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Locked Open Delay"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:1 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nﻞﻌﻔﻟﺎﺑ ﺎًﺣﻮﺘﻔﻣ ﺮﺧﺁ ﺓﺍﺩﺃ ﺢﻴﻤﻠﺗ ﻥﻮﻜﻳ ﺎﻣﺪﻨﻋ ﺕﺍﻭﺩﻷﺍ ﺕﺎﺤﻴﻤﻠﺗ ﻞﻔﻗ ﻞﺒﻗ ﺮﻴﺧﺄﺘﻟﺍ ﻂﺒﻀﻳ."
 # Audio
 SETTING_Sound_Effects:1 "ﻴﺗﻮﺼﻟﺍ ﺕﺍﺮﺛﺆﻤﻟﺍ ﻊﻴﻤﺟ"
 SETTING_Sound_Effects_TOOLTIP:1 "#T ﺔﻴﺗﻮﺼﻟﺍ ﺕﺍﺮﺛﺆﻤﻟﺍ ﻢﺠﺣ \n .ﺔﻴﺗﻮﺼﻟﺍ ﺕﺍﺮﺛﺆﻤﻟﺍ ﻞﻛ ﻢﺠﺣ ﻂﺒﻀﻳ !#"
 SETTING_Ambience:0 "ﻂﻴﺤﻤﻟﺍ ﻮﺠﻟﺍ"
 SETTING_Ambience_TOOLTIP:1 "#T Ambience Volume\n#!ﺔﻄﻴﺤﻤﻟﺍ ﺔﺌﻴﺒﻟﺍ ﻢﺠﺣ ﻂﺒﻀﻳ."
 SETTING_TOOLTIP_MODE:1 "ﺕﺍﻭﺩﻷﺍ ﺢﻴﻤﻠﺗ ﻊﺿﻭ"
 SETTING_TOOLTIP_MODE_TOOLTIP:3 "#T $SETTING_TOOLTIP_MODE$#!\nﺕﺍﻭﺩﻷﺍ ﺕﺎﺤﻴﻤﻠﺗ ﻲﻓ ﺕﺍﻭﺩﻷﺍ ﺕﺎﺤﻴﻤﻠﺗ ﺝﺍﺭﺩﺇ ﺢﻴﺘﻳ ﺎﻤﻣ ،ﺕﺍﻭﺩﻷﺍ ﺕﺎﺤﻴﻤﻠﺗ "ﻦﻴﻣﺄﺗ" ﺔﻘﻳﺮﻃ ﻂﺒﻀﻳ."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "ﺱﻭﺎﻤﻟﺍ ﻩﺎﺠﺗﺍ"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nTooltips automatically lock in place until the cursor moves away."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "ﻞﻤﻌﻟﺍ ﻞﻔﻗ"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nPress #V Middle Mouse#! to lock and unlock tooltips."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "ﺖﻗﺆﻤﻟﺍ ﻞﻔﻗ"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nﻞﻔﻘﻟﺍ ﺔﻟﺎﺣ ﻲﻓ ﺓﺩﻮﺟﻮﻣ ﺕﺍﻭﺩﻷﺍ ﺕﺎﺤﻴﻤﻠﺗ ﻥﺃ ﻻﺇ ،ﺮﺷﺆﻤﻟﺎﺑ ﻞﻤﻌﻳ ﻻ ﺔﻛﺮﺤﻠﻟ ﺮﻴﺼﻘﻟﺍ ﻑﺮﺤﻟﺍ ﻥﺃ ﻦﻣ ﻢﻏﺮﻟﺍ ﻰﻠﻋ. #weak (Default setting.)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "ﺕﺎﻗﺮﻔﺘﻣ"
 SETTINGS_CATEGORY_TOOLTIPS:0 "ﺕﺎﺤﻴﻤﻠﺗ"
 SETTINGS_CATEGORY_SFX:0 "ﺓﺩﺪﺤﻣ ﺔﻴﺗﻮﺻ ﺕﺍﺮﺛﺆﻣ"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "ﻡﺎﻋ"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "ﺔﻄﻳﺮﺨﻟﺍ ﻂﺑﺍﻮﺿ"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "ﺏﺎﻌﻟﻷﺍ ﻆﻔﺣ"
 SETTINGS_CATEGORY_LANGUAGE:0 "ﺔﻐﻟ"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "ﻡﺪﻘﺘﻣ"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "ﺭﻮﺻ"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "ﺓﺭﻮﺼﻣ ﺕﺎﺑﺎﺻﻹﺍﻭ ﺽﺍﺮﻣﻷﺍ ﺭﺎﻬﻇﺇ"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nﺕﺎﻴﺼﺨﺸﻟﺍ ﺭﻮﺻ ﻲﻓ ﺔﻴﺋﺮﻣ ﻥﻮﻜﺘﺳ ﺔﻴﻣﻮﺳﺮﻟﺍ ﺽﺍﺮﻣﻷﺍﻭ ﺕﺎﺑﺎﺻﻹﺍ ﺖﻧﺎﻛ ﺍﺫﺇ ﺎﻣ ﻂﺒﻀﻳ."
 NEVER:0 "ﺍﺪﺑﺃ"
 MONTHLY:0 "ﺮﻬﺷ ﻞﻛ"
 HALFYEAR:0 "ﺭﻮﻬﺷ 6 ﻞﻛ"
 YEARLY:0 "ﻡﺎﻋ ﻞﻛ"
 FIVE_YEAR:0 "ﺕﺍﻮﻨﺳ 5 ﻞﻛ"
 SETTINGS_CATEGORY_TUTORIAL:0 "ﺔﻴﻤﻴﻠﻌﺘﻟﺍ ﺓﺭﻭﺪﻟﺍ"
 SETTING_REACTIVE_TUTORIAL:1 "ﺔﻴﻠﻋﺎﻔﺘﻟﺍ ﺢﺋﺎﺼﻨﻟﺍ ﺽﺮﻋ"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\nﺩﺪﺠﻟﺍ ﻦﻴﺒﻋﻼﻟ ﺓﺪﻴﻔﻣ .ﺐﻌﻠﻟﺍ ﺔﻘﻳﺮﻃ ﻊﻣ ﻞﻋﺎﻔﺘﺗ ﺔﻴﻤﻴﻠﻌﺗ ﺔﺤﻴﺼﻧ ﺽﺮﻌﺗ ﻥﺃ ﺐﺠﻳ ﺔﺒﻌﻠﻟﺍ ﺖﻧﺎﻛ ﺍﺫﺇ ﺎﻣ ﺩﺪﺤﻳ."
 SETTING_SHOW_SUGGESTIONS:0 "ﺕﺎﺣﺍﺮﺘﻗﺍ ﺭﺎﻬﻇﺇ"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:2 "#T $SETTING_SHOW_SUGGESTIONS$#!\nﺩﺪﺠﻟﺍ ﻦﻴﺒﻋﻼﻟ ﺓﺪﻴﻔﻣ .ﺔﻤﻈﺘﻨﻣ ﺔﻴﻨﻣﺯ ﺕﺍﺮﺘﻓ ﻰﻠﻋ ﻪﺑ ﻡﺎﻴﻘﻟﺍ ﺐﺠﻳ ﺎًﺌﻴﺷ ﺡﺮﺘﻘﺗ ﻥﺃ ﺔﺒﻌﻠﻟﺍ ﻰﻠﻋ ﺐﺠﻳ ﻥﺎﻛ ﺍﺫﺇ ﺎﻣ ﺩﺪﺤﻳ"
 RESET_REACTIVE_ADVICE:0 " ﻦﻴﻴﻌﺗ ﺓﺩﺎﻋﺇ\nﺔﻴﻠﻋﺎﻔﺘﻟﺍ ﺢﺋﺎﺼﻨﻟﺍ"
 RESET_REACTIVE_ADVICE_TOOLTIP:1 "#T ﺔﻴﻠﻋﺎﻔﺘﻟﺍ ﺢﺋﺎﺼﻨﻟﺍ ﻦﻴﻴﻌﺗ ﺓﺩﺎﻋﺇ#!\n.ﻯﺮﺧﺃ ﺓﺮﻣ ﺎًﻘﺒﺴﻣ ﺎﻬﺗﺪﻫﺎﺸﻣ ﺖﻤﺗ ﻲﺘﻟﺍ ﺔﻴﻠﻋﺎﻔﺘﻟﺍ ﺢﺋﺎﺼﻨﻟﺍ ﺮﻬﻈﺘﺳ"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "ﺔﻴﻠﻋﺎﻔﺘﻟﺍ ﺢﺋﺎﺼﻨﻟﺍ ﻦﻴﻴﻌﺗ ﺓﺩﺎﻋﺇ"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "؟ﺔﻴﻠﻋﺎﻔﺘﻟﺍ ﺢﺋﺎﺼﻨﻟﺍ ﻦﻴﻴﻌﺗ ﺓﺩﺎﻋﺇ ﺪﻳﺮﺗ ﻚﻧﺃ ﺪﻛﺄﺘﻣ ﺖﻧﺃ ﻞﻫ"
 SETTING_ADVANCED_SHADERS:0 "ﺔﻣﺪﻘﺘﻣ ﻞﻴﻠﻈﺗ ﺕﺍﺮﻴﺛﺄﺗ"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T ﺔﻣﺪﻘﺘﻣ ﻞﻴﻠﻈﺗ ﺕﺍﺮﻴﺛﺄﺗ\n#!.ﺔﻣﺪﻘﺘﻤﻟﺍ ﻞﻴﻠﻈﺘﻟﺍ ﺕﺍﺮﻴﺛﺄﺗ ﻦﻴﻜﻤﺗ ﻰﻟﺇ ﺭﺎﻴﺨﻟﺍ ﺍﺬﻫ ﻱﺩﺆﻴﺳ\n\nﺃﻮﺳﺃ ﻭﺪﺒﺗ (ﻩﺎﻴﻤﻟﺍﻭ ﺲﻳﺭﺎﻀﺘﻟﺍ ﻞﺜﻣ) ﺕﺍﺮﻴﺛﺄﺘﻟﺍ ﺾﻌﺑ ﻞﻌﺟ ﺏﺎﺴﺣ ﻰﻠﻋ ﺀﺍﺩﻷﺍ ﺓﺩﺎﻳﺯ ﻰﻟﺇ ﻪﻠﻴﻐﺸﺗ ﻑﺎﻘﻳﺇ ﻱﺩﺆﻳ ﺪﻗ"
 BASED_ON_ZOOM_LEVEL:0 "ﻲﻜﻴﻣﺎﻨﻳﺩ"
 ALWAYS_HIDE:0 "ﺎﻤﺋﺍﺩ ﺊﺒﺘﺧﺍ"
 ALWAYS_SHOW:0 "ﺎﻤﺋﺍﺩ ﺽﺮﻋﺍ"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "ﺔﻴﻠﺣﺎﺴﻟﺍ ﺩﻭﺪﺤﻟﺍ"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\n.ﻲﻠﺣﺎﺴﻟﺍ ﻝﺎﺠﻤﻟﺍ ﺩﻭﺪﺣ ﺭﺎﻬﻇﺇ ﺐﺠﻳ ﻰﺘﻣ ﻲﻓ ﺭﺎﻴﺨﻟﺍ ﺍﺬﻫ ﻢﻜﺤﺘﻴﺳ\nﺍﺫﺃ $BASED_ON_ZOOM_LEVEL$ .ﻞﻴﺻﺎﻔﺘﻟﺍ ﺮﻴﺒﻜﺗ ﻯﻮﺘﺴﻣ ﻲﻓ ﺎﻫﺅﺎﻔﺧﺇ ﻢﺘﻴﺳ ﻢﺛ\n\nﺭﺎﻴﺘﺧﺍ $ALWAYS_SHOW$ ﻭﺃ $ALWAYS_HIDE$ .ﺎًﻴﻜﻴﻣﺎﻨﻳﺩ ﻲﻠﺣﺎﺴﻟﺍ ﻢﻟﺎﻌﻟﺍ ﺩﻭﺪﺣ ﺀﺎﻔﺧﺇ ﻡﺪﻋ ﺏﺎﺴﺣ ﻰﻠﻋ ﺀﺍﺩﻷﺍ ﺓﺩﺎﻳﺯ ﻰﻟﺇ ﻱﺩﺆﻳ ﺪﻗ"
 
